#!/bin/bash
#
# Jeff Wang (jeffawang@gmail.com)
# 2015-12-09
#

# Display commands as they are run

main() {
    base=$(pwd)
    echo base: $base

    # git submodule init
    # git submodule update

    # Backup existing dotfiles, replace them with links
    [ -d bak ] && mkdir -pv bak
    for rc in *rc *profile tmux.conf vim tmux; do
      [ -L ~/.$rc ] && rm ~/.$rc
      [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
      ln -sfv $base/$rc ~/.$rc
    done

    # Make the directory structure I like
    for i in files code bin .bash; do
      mkdir -pv ~/${i}
    done

    for i in bin/*; do
      ln -sfv $base/${i} ~/${i}
    done

    for i in nvim; do
      ln -sfv $base/${i} ~/.config/"${i}"
    done

    # Homebrew
    if [ $(uname -s) = 'Darwin' ]; then
      # rev from 2026-04-14
      rev=e03d55ac120da75d8a03c207cbd9a17d89f3b04b
      [ -z "$(which brew)" ] &&
        bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/${rev}/install)"

      brew bundle
    fi
}

cd "$(dirname "$BASH_SOURCE")"
main
