#!/bin/bash
#
# Jeff Wang (jeffawang@gmail.com)
# 2015-12-09
#

# Display commands as they are run

main() {
    base=$(pwd)

    git submodule init
    git submodule update

    # Backup existing dotfiles, replace them with links
    [ -d bak ] && mkdir -pv bak
    for rc in *rc *profile tmux.conf vim tmux; do
      [ -L ~/.$rc ] && rm ~/.$rc
      [ -e ~/.$rc ] && mv -v ~/.$rc bak/.$rc
      ln -sfv $base/$rc ~/.$rc
    done

    # Make the directory structure I like
    for i in files code bin; do
      mkdir -pv ~/${i}
    done

    for i in bin/*; do
      ln -sfv $base/${i} ~/${i}
    done

    # Homebrew
    if [ $(uname -s) = 'Darwin' ]; then
      [ -z "$(which brew)" ] &&
        ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

      brew tap Homebrew/bundle
      brew bundle
    fi
}

# Remember where we started, but cd to the script's directory
original_dir=$(pwd)
cd $(dirname $BASH_SOURCE)
main
cd $original_dir
